version: "3.9"

services:
  httpd:
    build: ./httpd
    ports:
      - "80:80"
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
    networks:
      - coffee-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/coffee_shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=coffee_shop_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql
    networks:
      - coffee-network
    command: ["sh", "-c", "sleep 50 && java -jar inventory-service.jar"]

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/coffee_shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=coffee_shop_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - INVENTORY_URL=http://inventory-service:8082
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql
      - inventory-service
    networks:
      - coffee-network
    command: ["sh", "-c", "sleep 50 && java -jar order-service.jar"]

  mysql:  
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=coffee_shop
      - MYSQL_USER=coffee_shop_user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - coffee-network
networks:
  coffee-network:
    driver: bridge
