version: "3.9"

services:
  httpd:
    build: ./httpd
    ports:
      - "80:80"

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/coffee_shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=coffee_shop_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/coffee_shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=coffee_shop_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - INVENTORY_URL=http://inventory-service:8082
    depends_on:
      - mysql
      - inventory-service

  mysql:  
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=coffee_shop
      - MYSQL_USER=coffee_shop_user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
