inventory:
  url: http://inventory-service:8082

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/coffee_shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC # Replace <your_database_name>
    username: coffee_shop_user # Replace
    password: password # Replace
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Or none for production
    show-sql: true # Optional
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
